import type { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: "AI Built App",
  description: "Generated by TBC AI Tools",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-background">
      <body>{children}</body>
    </html>
  )
}
